version: '3'

services:
  loyalty-proxy-rpc:
    container_name: loyalty-proxy-rpc
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:5001
    env_file:
      - .env
    volumes:
      - ./data:/app/public
  
  redis:
    container_name: be-redis
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - REDIS_PASSWORD=${REDIS_PASSWORD}
